### ISSUE TITLE
The latest LOS ROM will check the firmware and only supports to V10.0.1.0.OCAMIFH, or will give error 7

### ISSUE THREAD

**Issue by timeneverdie** [xiaomi-msm8998/android_device_xiaomi_sagit#1]
According to [this site](https://xiaomifirmwareupdater.com), sagit has the firmware below:

V10.3.1.0.OCACNXM | 8.0 | 2019-06-04 | Chinese 
V10.3.4.0.OCAMIXM | 8.0 | 2019-06-04 | Global 
V10.2.1.0.OCACNFK | 8.0 | 2019-04-12 | Chinese 
V10.3.1.0.OCACNXM | 8.0 | 2019-04-09 | Chinese 
V10.2.1.0.OCAMIXM | 8.0 | 2019-02-19 | Global 
V10.2.1.0.OCACNFK | 8.0 | 2019-01-02 | Chinese 
V10.0.2.0.OCACNFH | 8.0 | 2018-10-16 | Chinese 
V10.0.1.0.OCAMIFH | 8.0 | 2018-09-19 | Global 
V10.0.1.0.OCACNFH | 8.0 | 2018-09-10 | Chinese 
V9.6.3.0.OCACNFD | 8.0 | 2018-08-09 | Chinese 
V9.6.2.0.OCACNFD | 8.0 | 2018-07-20 | Chinese 
V9.5.8.0.OCAMIFA | 8.0 | 2018-07-20 | Global 

But the LOS will check the firmware first and only supports to V10.0.1.0.OCAMIFH, nearly one year ago.

If the firmware is too latest, it will get the error code of 7 in TWRP. It says: "xiaomi.verify_trustzone("TZ.BF.4.0.6-00124","TZ.BF.4.0.6-00130") == '1' ". If users have fastboot flashed via official MIUI ROMs, the firmware will automatically be the latest and cannot install LOS.

If we want to go with it, we only have three ways:

1. Developer changes the script (recommended)
2. Downgrade the firmware in TWRP (not known for everyone and lack of the latest support)
3. Edit the script yourself in the editor [like this](http://www.lineageosdownloads.com/fix-error-7-lineage-os/) (have difficulties and highly risk of breaking the files)

I have researched it for much time, and wish developers can focus on this problem. But I still don't know the script was set by sagit developer, LOS developer or Google Android developer. If this is due to LOS official or Google Android official, please inform them to update it.

Thanks.

**Comment by ArianK16a** [comment]
Hey, the trustzone value/firmware version requirement is set from: https://github.com/LineageOS/android_device_xiaomi_msm8998-common/blob/lineage-16.0/board-info.txt which hasn't been updated since a year. This is because we have the bringup for the pie firmware still pending at the lineageos gerrit, it will get merged soon. Until then we are sticking with the old firmwares because they work just fine and a downgrade is always possible without any problems.

**Comment by timeneverdie** [comment]
> Hey, the trustzone value/firmware version requirement is set from: https://github.com/LineageOS/android_device_xiaomi_msm8998-common/blob/lineage-16.0/board-info.txt which hasn't been updated since a year. This is because we have the bringup for the pie firmware still pending at the lineageos gerrit, it will get merged soon. Until then we are sticking with the old firmwares because they work just fine and a downgrade is always possible without any problems.

Since sagit MIUI official Pie ROM has been released out, when will the latest firmware be supported?

**Comment by ArianK16a** [comment]
It is supported since 2 days.

**Comment by timeneverdie** [comment]
> It is supported since 2 days.

Really? Which version of the firmware is recommended?

**Comment by ArianK16a** [comment]
The global stable 10.4.1.0

**Comment by timeneverdie** [comment]
> The global stable 10.4.1.0

Wow, that's wonderful! Good job! I'll flash it. If I find any issue, I'll report. Thanks for your nice work!
