### ISSUE TITLE
building problem

### ISSUE THREAD

**Issue by laijirong** [xiaomi-msm8998/android_device_xiaomi_sagit#2]
ninja: error: '/android/lineage/out/target/common/obj/JAVA_LIBRARIES/WfdCommon_intermediates/classes.jar', needed by '/android/lineage/out/target/common/obj/PACKAGING/boot-jars-package-check_intermediates/stamp', missing and no known rule to make it
00:24:02 ninja failed with: exit status 1

What`s wrong with it?

**Comment by ArianK16a** [comment]
could you share the used local_manifests?
