### ISSUE TITLE
The mobile network and GPS signal will lose only if toggle airplane mode

### ISSUE THREAD

**Issue by timeneverdie** [xiaomi-msm8998/android_device_xiaomi_sagit#3]
I have met this problem across many versions of LOS for sagit. Now I'm very sure this is a serious problem.

After connecting network via 4G, it will lose network background for a while and it doesn't show any information about it until you find there is no connection for browsing apps or websites.

After toggling airplane mode, it will refresh and recover.

And also, I find GPS signal will be affected. You cannot use Map apps to get your location until toggling the airplane mode.

LOS version is on of the latest one: 16.0-20190925.
Firmware version is the latest one: V10.4.1.0.PCAMIXM

**Comment by ArianK16a** [comment]
ehm, what? You mean mobile data and GPS doesn't work until you enable and disable airplane mode?
